# Generated by Django 4.1.3 on 2023-06-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to=None)),
                ('link', models.URLField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
            },
        ),
    ]
